[package]
name = "fantoccini-test"
version = "0.1.0"
authors = ["André Claudino <claudino@d2x.com.br>"]
edition = "2018"

[dependencies]
fantoccini = "0.17.3"
url = "2.2.1"
async-recursion = "0.3.2"

structopt = "0.3"

tokio = {version = "1.4.0", features = ["macros", "rt-multi-thread"]}